### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by EAT-CODE-KITE-REPEAT** [EAT-CODE-KITE-REPEAT/graphql-define#1]
Start with GraphQLDefine: 1 GitHub repo, 2 npm packages (RN and Node). First do node.

- [ ] How to put all connections/relations of belongsTo/hasMany into the model? Create associations object for every model
- [ ] Make sync function trust on model, test this
- [ ] Refactor backend the way I want the input/output to be (put to-be-lib in different folder), and test if it still works
- [ ] test with sqlite (if it seems this is possible (https://stackoverflow.com/questions/751160/mysql-and-sqlite-differences-in-sql) so it would be great if I can easily switch between them, even using 'connection')
- [ ] If it's stable enough, separate it all from the codebase, publish it, and try to use it with library
- [ ] If backend works, create front-end package too
- [ ] Create docs
